version: '2'
services:
  <%= appname %>:
    image: chatopshpe/hubot-enterprise
    volumes:
      - .:/integration
    environment:
      - ADAPTER=slack
      - HUBOT_APP_TOKEN=xoxb-000000000-XXXXXXXXXXXXXXXXXX
      - HUBOT_SLACK_TOKEN=xoxb-0000000000-XXXXXXXXXXXXXXXXXXXXXX
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - no_proxy=$no_proxy
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTPS_PROXY
      - NO_PROXY=$NO_PROXY
